# Generated by Django 6.0.4 on 2026-04-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_project_owner_remove_project_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Scrum Master', 'Scrum Master'), ('Product Owner', 'Product Owner'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('Observer', 'Observer')], default='Developer', max_length=20, verbose_name='Rol ofrecido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=12, verbose_name='Estado')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de invitacion')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_project_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario invitado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Invitacion de proyecto',
                'verbose_name_plural': 'Invitaciones de proyecto',
                'ordering': ['-created_at'],
            },
        ),
    ]
