# Generated by Django 5.2.8 on 2026-05-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(verbose_name='Horas')),
                ('logged_by', models.CharField(default='Usuario', max_length=150, verbose_name='Registrado por')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='accounts.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Registro de tiempo',
                'verbose_name_plural': 'Registros de tiempo',
                'ordering': ['-date'],
            },
        ),
    ]
