# Generated by Django 5.2.8 on 2026-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_project_id_alter_projectinvitation_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE accounts_task SET assignee = NULL WHERE assignee IS NOT NULL AND assignee REGEXP '[^0-9]'",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Responsable (ID)'),
        ),
    ]