# Generated by Django 6.0.4 on 2026-05-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_project_id_alter_projectinvitation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del sprint'),
        ),
    ]
